name: Daily heartbeat commit

on:
  schedule:
    - cron: "0 2 * * *" # every day at 02:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Update heartbeat file
        run: |
          mkdir -p .github
          date -u "+%Y-%m-%dT%H:%M:%SZ" > .github/heartbeat.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/heartbeat.txt
          git commit -m "chore: daily heartbeat [skip ci]" || echo "No changes to commit"
          git push
